### ISSUE TITLE
tutorial might not run without python shebang

### ISSUE THREAD

**Issue by orrblue** [rickstaa/moveit-tutorials-python-examples#1]
The pick_and_place python ros node file might not run properly. Add this to the top of the file: `#!/usr/bin/env python3` as is customary for all python scripts

**Comment by rickstaa** [comment]
Sorry for the late reply. Thanks for your bug report. I applied your fix in 3e59be29f243f1b9655e73cd691a08e36d718043. This commit is included in https://github.com/rickstaa/moveit-tutorials-python-examples/releases/tag/v1.0.1.
