### ISSUE TITLE
cmakelists

### ISSUE THREAD

**Issue by zhangyiian** [rickstaa/moveit-tutorials-python-examples#2]
should be

```
install(PROGRAMS
  scripts/pick_place_tutorial.py
  DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION}
```

**Comment by rickstaa** [comment]
@zhangyiian Thanks for letting me know. 😄 Feel free to create a PR, and I will merge it into the main branch.

**Comment by rickstaa** [comment]
@zhangyiian I fixed this in https://github.com/rickstaa/moveit-tutorials-python-examples/releases/tag/v1.0.5.
